### PR TITLE
Simple landing page with login button

### PR DESCRIPTION
**Pull request by denis1stomin**
Very simple landing page which doesn't need authentication to see it.
@preigile  I couldn't understand how to make the message in the center of the page :smile:

### CODE REVIEW

**Comment by skalitin** [comment]
> @preigile I couldn't understand how to make the message in the center of the page 😄

Do you mean something like this? 
image
This works for me:
```
 .centered-suggestion-message {
    display: flex;
    font-size: 1.2em;
    margin-top: 40px;
    
      span {
        display: table;
        margin:0 auto;
      }
  }
```

**Comment by skalitin** [comment]
I've  already seen this mysterious Vue issue: `<HeaderTitle></HeaderTitle>` works fine, but `<HeaderTitle/>` stops rendering all the elements in the containing element - so there was no 'Log In' link.

**Comment by skalitin** [comment]
Initially looked like this in my chrome:
image
So I removed grey 'menu' stuff.

**Review by skalitin — APPROVED** [review]
@denis1stomin Updated a bit and approved, please check.

**Comment by denis1stomin** [comment]
Cool. Thanks!
BTW Do you use parcel web server or run `npm run build` and than use some other static files server?

**Comment by denis1stomin** [comment]
Checked. Works as should.

**Comment by skalitin** [comment]
parcel web server

**Pull request merged**
